numero_tabuada = int(input("Digite qual tabuada deseja: "))
print(f"TABUADA DO {numero_tabuada}".center(18))
print(f"{numero_tabuada} x 0 = {numero_tabuada * 0}")
print(f"{numero_tabuada} x 1 = {numero_tabuada * 1}")
print(f"{numero_tabuada} x 2 = {numero_tabuada * 2}")
print(f"{numero_tabuada} x 3 = {numero_tabuada * 3}")
print(f"{numero_tabuada} x 4 = {numero_tabuada * 4}")
print(f"{numero_tabuada} x 5 = {numero_tabuada * 5}")
print(f"{numero_tabuada} x 6 = {numero_tabuada * 6}")
print(f"{numero_tabuada} x 7 = {numero_tabuada * 7}")
print(f"{numero_tabuada} x 8 = {numero_tabuada * 8}")
print(f"{numero_tabuada} x 9 = {numero_tabuada * 9}")
print(f"{numero_tabuada} x 10 = {numero_tabuada * 10}")
